/*
Package repositories hosts any and all code related to interacting with a database. Each file
is broken down by an individual database table where the table is the primary focus of the query.
*/
package repositories

import (
	"github.com/JoRyGu/solo_stylist/data/models"
	"github.com/jmoiron/sqlx"
)

// AccountsRepository models the repository whose primary focus is on the "users" table.
type AccountsRepository struct {
	db *sqlx.DB
}

// NewAccountsRepository generates a reference to an instance of the AccountsRepository struct
// and injects an instance of sqlx.DB for internal use.
func NewAccountsRepository(db *sqlx.DB) *AccountsRepository {
	return &AccountsRepository{db}
}

// GetAll retrieves all columns and rows of the "users" table from the database.
func (ar *AccountsRepository) GetAll() ([]*models.Account, error) {
	accounts := []*models.Account{}
	err := ar.db.Select(&accounts, "select * from users")
	if err != nil {
		return nil, err
	}

	return accounts, nil
}

// GetById retrieves all columns of a row on the "users" table where the id column matches the passed id.
func (ar *AccountsRepository) GetById(id int) (*models.Account, error) {
	account := &models.Account{}

	if err := ar.db.Get(account, "select * from users where id = $1", id); err != nil {
		return nil, err
	}

	return account, nil
}

// Create creates a new row on the "users" table in the database. It also populates the Id property on the
// instance of *models.Account with the serialized ID generated by the database.
func (ar *AccountsRepository) Create(a *models.Account) error {
	var lastInsertId int

	row := ar.db.QueryRowx("insert into users (first_name, last_name, email, password, created_on, updated_on) values ($1, $2, $3, $4, $5, $6) returning id",
		a.FirstName, a.LastName, a.Email, a.Password, a.CreatedOn, a.UpdatedOn)

	err := row.Scan(&lastInsertId)
	if err != nil {
		return err
	}

	a.Id = lastInsertId

	return nil
}

// func (ar *AccountsRepository) Update(a *models.Account) error {

// }
